[package]
name = "flotsam"
version = "0.1.0"
edition = "2021"

[dependencies]
digitalocean = "0.1.1"
dotenv = "0.15.0"
tokio = "1.39.2"
clap = { version = "4.5.13", features = ["derive"] }
strsim = "0.11.1"
